import { chromium } from "playwright";
const browser = await chromium.launch({ channel: "chrome", headless: true });
const ctx = await browser.newContext({ viewport: { width: 1400, height: 1000 } });
const page = await ctx.newPage();
await page.goto("http://localhost:3000/auth", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.fill('input[type="email"]', "test-admin@isa.demo");
await page.fill('input[type="password"]', "DemoPortal2026!");
await page.click('button[type="submit"]:has-text("Sign in")');
await page.waitForURL(u => !u.pathname.startsWith("/auth"), { timeout: 20000 });
await page.waitForTimeout(3500);
const main = await page.locator("main").innerText();
const risk = main.match(/(\d+)\s*at-risk/);
console.log("at-risk now:", risk ? risk[1] : "?");
await browser.close();
