export const CALL_NOTE_TEMPLATES: { key: string; label: string; body: string }[] = [
  {
    key: "weekly",
    label: "Weekly check-in",
    body: [
      "## What went well this week",
      "- ",
      "",
      "## Blockers / friction",
      "- ",
      "",
      "## Application activity",
      "- Apps submitted:",
      "- Interviews:",
      "",
      "## Focus for next week",
      "- ",
    ].join("\n"),
  },
  {
    key: "mock",
    label: "Mock interview",
    body: [
      "## Role / company mocked",
      "- ",
      "",
      "## Strengths",
      "- ",
      "",
      "## Gaps to close",
      "- ",
      "",
      "## Homework",
      "- ",
    ].join("\n"),
  },
  {
    key: "offer",
    label: "Offer negotiation",
    body: [
      "## Offer details",
      "- Base / OTE:",
      "- Deadline:",
      "",
      "## Leverage",
      "- ",
      "",
      "## Counter plan",
      "- ",
    ].join("\n"),
  },
  {
    key: "kickoff",
    label: "Kickoff / onboarding",
    body: [
      "## Background & goals",
      "- ",
      "",
      "## Target roles",
      "- ",
      "",
      "## First 30-day plan",
      "- ",
    ].join("\n"),
  },
];
