/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintRouteImport } from './routes/print'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated.work'
import { Route as AuthenticatedTestimonialsRouteImport } from './routes/_authenticated.testimonials'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated.team'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated.students'
import { Route as AuthenticatedStudentSuccessRouteImport } from './routes/_authenticated.student-success'
import { Route as AuthenticatedStudentPortalRouteImport } from './routes/_authenticated.student-portal'
import { Route as AuthenticatedSopsRouteImport } from './routes/_authenticated.sops'
import { Route as AuthenticatedSalesHqRouteImport } from './routes/_authenticated.sales-hq'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated.sales'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated.revenue'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated.policies'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated.performance'
import { Route as AuthenticatedPayoutsRouteImport } from './routes/_authenticated.payouts'
import { Route as AuthenticatedMochiRouteImport } from './routes/_authenticated.mochi'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated.knowledge'
import { Route as AuthenticatedInstallmentsRouteImport } from './routes/_authenticated.installments'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated.finance'
import { Route as AuthenticatedEodsRouteImport } from './routes/_authenticated.eods'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated.directory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated.customers'
import { Route as AuthenticatedCsmRouteImport } from './routes/_authenticated.csm'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated.crm'
import { Route as AuthenticatedCloserResourcesRouteImport } from './routes/_authenticated.closer-resources'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated.calls'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedActionItemsRouteImport } from './routes/_authenticated.action-items'
import { Route as AuthenticatedPoliciesIndexRouteImport } from './routes/_authenticated.policies.index'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated.knowledge.index'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google-oauth-callback'
import { Route as AuthenticatedTeamIdRouteImport } from './routes/_authenticated.team_.$id'
import { Route as AuthenticatedStudentsRequestsRouteImport } from './routes/_authenticated.students.requests'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated.students.$id'
import { Route as AuthenticatedSopsIsaSettingProcessRouteImport } from './routes/_authenticated.sops.isa-setting-process'
import { Route as AuthenticatedSopsDmSettingMasteryRouteImport } from './routes/_authenticated.sops.dm-setting-mastery'
import { Route as AuthenticatedPoliciesEodHygieneRouteImport } from './routes/_authenticated.policies.eod-hygiene'
import { Route as AuthenticatedPoliciesCrmHygieneRouteImport } from './routes/_authenticated.policies.crm-hygiene'
import { Route as AuthenticatedKnowledgeNewRouteImport } from './routes/_authenticated.knowledge.new'
import { Route as AuthenticatedKnowledgeSlugRouteImport } from './routes/_authenticated.knowledge.$slug'
import { Route as AuthenticatedKnowledgeSlugEditRouteImport } from './routes/_authenticated.knowledge.$slug.edit'

const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestimonialsRoute =
  AuthenticatedTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentSuccessRoute =
  AuthenticatedStudentSuccessRouteImport.update({
    id: '/student-success',
    path: '/student-success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentPortalRoute =
  AuthenticatedStudentPortalRouteImport.update({
    id: '/student-portal',
    path: '/student-portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSopsRoute = AuthenticatedSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesHqRoute = AuthenticatedSalesHqRouteImport.update({
  id: '/sales-hq',
  path: '/sales-hq',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayoutsRoute = AuthenticatedPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMochiRoute = AuthenticatedMochiRouteImport.update({
  id: '/mochi',
  path: '/mochi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstallmentsRoute =
  AuthenticatedInstallmentsRouteImport.update({
    id: '/installments',
    path: '/installments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEodsRoute = AuthenticatedEodsRouteImport.update({
  id: '/eods',
  path: '/eods',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCsmRoute = AuthenticatedCsmRouteImport.update({
  id: '/csm',
  path: '/csm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCloserResourcesRoute =
  AuthenticatedCloserResourcesRouteImport.update({
    id: '/closer-resources',
    path: '/closer-resources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActionItemsRoute =
  AuthenticatedActionItemsRouteImport.update({
    id: '/action-items',
    path: '/action-items',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPoliciesIndexRoute =
  AuthenticatedPoliciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google-oauth-callback',
    path: '/api/public/google-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeamIdRoute = AuthenticatedTeamIdRouteImport.update({
  id: '/team_/$id',
  path: '/team/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRequestsRoute =
  AuthenticatedStudentsRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const AuthenticatedSopsIsaSettingProcessRoute =
  AuthenticatedSopsIsaSettingProcessRouteImport.update({
    id: '/isa-setting-process',
    path: '/isa-setting-process',
    getParentRoute: () => AuthenticatedSopsRoute,
  } as any)
const AuthenticatedSopsDmSettingMasteryRoute =
  AuthenticatedSopsDmSettingMasteryRouteImport.update({
    id: '/dm-setting-mastery',
    path: '/dm-setting-mastery',
    getParentRoute: () => AuthenticatedSopsRoute,
  } as any)
const AuthenticatedPoliciesEodHygieneRoute =
  AuthenticatedPoliciesEodHygieneRouteImport.update({
    id: '/eod-hygiene',
    path: '/eod-hygiene',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPoliciesCrmHygieneRoute =
  AuthenticatedPoliciesCrmHygieneRouteImport.update({
    id: '/crm-hygiene',
    path: '/crm-hygiene',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedKnowledgeNewRoute =
  AuthenticatedKnowledgeNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedKnowledgeSlugRoute =
  AuthenticatedKnowledgeSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedKnowledgeSlugEditRoute =
  AuthenticatedKnowledgeSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedKnowledgeSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/print': typeof PrintRoute
  '/action-items': typeof AuthenticatedActionItemsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/closer-resources': typeof AuthenticatedCloserResourcesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/csm': typeof AuthenticatedCsmRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/eods': typeof AuthenticatedEodsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/installments': typeof AuthenticatedInstallmentsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/mochi': typeof AuthenticatedMochiRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/sales-hq': typeof AuthenticatedSalesHqRoute
  '/sops': typeof AuthenticatedSopsRouteWithChildren
  '/student-portal': typeof AuthenticatedStudentPortalRoute
  '/student-success': typeof AuthenticatedStudentSuccessRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/testimonials': typeof AuthenticatedTestimonialsRoute
  '/work': typeof AuthenticatedWorkRoute
  '/knowledge/$slug': typeof AuthenticatedKnowledgeSlugRouteWithChildren
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/policies/crm-hygiene': typeof AuthenticatedPoliciesCrmHygieneRoute
  '/policies/eod-hygiene': typeof AuthenticatedPoliciesEodHygieneRoute
  '/sops/dm-setting-mastery': typeof AuthenticatedSopsDmSettingMasteryRoute
  '/sops/isa-setting-process': typeof AuthenticatedSopsIsaSettingProcessRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/requests': typeof AuthenticatedStudentsRequestsRoute
  '/team/$id': typeof AuthenticatedTeamIdRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/knowledge/$slug/edit': typeof AuthenticatedKnowledgeSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/print': typeof PrintRoute
  '/action-items': typeof AuthenticatedActionItemsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/closer-resources': typeof AuthenticatedCloserResourcesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/csm': typeof AuthenticatedCsmRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/eods': typeof AuthenticatedEodsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/installments': typeof AuthenticatedInstallmentsRoute
  '/mochi': typeof AuthenticatedMochiRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/sales-hq': typeof AuthenticatedSalesHqRoute
  '/sops': typeof AuthenticatedSopsRouteWithChildren
  '/student-portal': typeof AuthenticatedStudentPortalRoute
  '/student-success': typeof AuthenticatedStudentSuccessRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/testimonials': typeof AuthenticatedTestimonialsRoute
  '/work': typeof AuthenticatedWorkRoute
  '/knowledge/$slug': typeof AuthenticatedKnowledgeSlugRouteWithChildren
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/policies/crm-hygiene': typeof AuthenticatedPoliciesCrmHygieneRoute
  '/policies/eod-hygiene': typeof AuthenticatedPoliciesEodHygieneRoute
  '/sops/dm-setting-mastery': typeof AuthenticatedSopsDmSettingMasteryRoute
  '/sops/isa-setting-process': typeof AuthenticatedSopsIsaSettingProcessRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/requests': typeof AuthenticatedStudentsRequestsRoute
  '/team/$id': typeof AuthenticatedTeamIdRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/policies': typeof AuthenticatedPoliciesIndexRoute
  '/knowledge/$slug/edit': typeof AuthenticatedKnowledgeSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/print': typeof PrintRoute
  '/_authenticated/action-items': typeof AuthenticatedActionItemsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/closer-resources': typeof AuthenticatedCloserResourcesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/csm': typeof AuthenticatedCsmRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRoute
  '/_authenticated/eods': typeof AuthenticatedEodsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/installments': typeof AuthenticatedInstallmentsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/_authenticated/mochi': typeof AuthenticatedMochiRoute
  '/_authenticated/payouts': typeof AuthenticatedPayoutsRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/sales-hq': typeof AuthenticatedSalesHqRoute
  '/_authenticated/sops': typeof AuthenticatedSopsRouteWithChildren
  '/_authenticated/student-portal': typeof AuthenticatedStudentPortalRoute
  '/_authenticated/student-success': typeof AuthenticatedStudentSuccessRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/testimonials': typeof AuthenticatedTestimonialsRoute
  '/_authenticated/work': typeof AuthenticatedWorkRoute
  '/_authenticated/knowledge/$slug': typeof AuthenticatedKnowledgeSlugRouteWithChildren
  '/_authenticated/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/_authenticated/policies/crm-hygiene': typeof AuthenticatedPoliciesCrmHygieneRoute
  '/_authenticated/policies/eod-hygiene': typeof AuthenticatedPoliciesEodHygieneRoute
  '/_authenticated/sops/dm-setting-mastery': typeof AuthenticatedSopsDmSettingMasteryRoute
  '/_authenticated/sops/isa-setting-process': typeof AuthenticatedSopsIsaSettingProcessRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/students/requests': typeof AuthenticatedStudentsRequestsRoute
  '/_authenticated/team_/$id': typeof AuthenticatedTeamIdRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/_authenticated/knowledge/$slug/edit': typeof AuthenticatedKnowledgeSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/print'
    | '/action-items'
    | '/admin'
    | '/analytics'
    | '/calendar'
    | '/calls'
    | '/chat'
    | '/closer-resources'
    | '/crm'
    | '/csm'
    | '/customers'
    | '/dashboard'
    | '/directory'
    | '/eods'
    | '/finance'
    | '/installments'
    | '/knowledge'
    | '/mochi'
    | '/payouts'
    | '/performance'
    | '/policies'
    | '/profile'
    | '/revenue'
    | '/sales'
    | '/sales-hq'
    | '/sops'
    | '/student-portal'
    | '/student-success'
    | '/students'
    | '/team'
    | '/testimonials'
    | '/work'
    | '/knowledge/$slug'
    | '/knowledge/new'
    | '/policies/crm-hygiene'
    | '/policies/eod-hygiene'
    | '/sops/dm-setting-mastery'
    | '/sops/isa-setting-process'
    | '/students/$id'
    | '/students/requests'
    | '/team/$id'
    | '/api/public/google-oauth-callback'
    | '/knowledge/'
    | '/policies/'
    | '/knowledge/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/print'
    | '/action-items'
    | '/admin'
    | '/analytics'
    | '/calendar'
    | '/calls'
    | '/chat'
    | '/closer-resources'
    | '/crm'
    | '/csm'
    | '/customers'
    | '/dashboard'
    | '/directory'
    | '/eods'
    | '/finance'
    | '/installments'
    | '/mochi'
    | '/payouts'
    | '/performance'
    | '/profile'
    | '/revenue'
    | '/sales'
    | '/sales-hq'
    | '/sops'
    | '/student-portal'
    | '/student-success'
    | '/students'
    | '/team'
    | '/testimonials'
    | '/work'
    | '/knowledge/$slug'
    | '/knowledge/new'
    | '/policies/crm-hygiene'
    | '/policies/eod-hygiene'
    | '/sops/dm-setting-mastery'
    | '/sops/isa-setting-process'
    | '/students/$id'
    | '/students/requests'
    | '/team/$id'
    | '/api/public/google-oauth-callback'
    | '/knowledge'
    | '/policies'
    | '/knowledge/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/print'
    | '/_authenticated/action-items'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/calls'
    | '/_authenticated/chat'
    | '/_authenticated/closer-resources'
    | '/_authenticated/crm'
    | '/_authenticated/csm'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/directory'
    | '/_authenticated/eods'
    | '/_authenticated/finance'
    | '/_authenticated/installments'
    | '/_authenticated/knowledge'
    | '/_authenticated/mochi'
    | '/_authenticated/payouts'
    | '/_authenticated/performance'
    | '/_authenticated/policies'
    | '/_authenticated/profile'
    | '/_authenticated/revenue'
    | '/_authenticated/sales'
    | '/_authenticated/sales-hq'
    | '/_authenticated/sops'
    | '/_authenticated/student-portal'
    | '/_authenticated/student-success'
    | '/_authenticated/students'
    | '/_authenticated/team'
    | '/_authenticated/testimonials'
    | '/_authenticated/work'
    | '/_authenticated/knowledge/$slug'
    | '/_authenticated/knowledge/new'
    | '/_authenticated/policies/crm-hygiene'
    | '/_authenticated/policies/eod-hygiene'
    | '/_authenticated/sops/dm-setting-mastery'
    | '/_authenticated/sops/isa-setting-process'
    | '/_authenticated/students/$id'
    | '/_authenticated/students/requests'
    | '/_authenticated/team_/$id'
    | '/api/public/google-oauth-callback'
    | '/_authenticated/knowledge/'
    | '/_authenticated/policies/'
    | '/_authenticated/knowledge/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrintRoute: typeof PrintRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/testimonials': {
      id: '/_authenticated/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof AuthenticatedTestimonialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-success': {
      id: '/_authenticated/student-success'
      path: '/student-success'
      fullPath: '/student-success'
      preLoaderRoute: typeof AuthenticatedStudentSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-portal': {
      id: '/_authenticated/student-portal'
      path: '/student-portal'
      fullPath: '/student-portal'
      preLoaderRoute: typeof AuthenticatedStudentPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sops': {
      id: '/_authenticated/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof AuthenticatedSopsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales-hq': {
      id: '/_authenticated/sales-hq'
      path: '/sales-hq'
      fullPath: '/sales-hq'
      preLoaderRoute: typeof AuthenticatedSalesHqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payouts': {
      id: '/_authenticated/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mochi': {
      id: '/_authenticated/mochi'
      path: '/mochi'
      fullPath: '/mochi'
      preLoaderRoute: typeof AuthenticatedMochiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/installments': {
      id: '/_authenticated/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof AuthenticatedInstallmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eods': {
      id: '/_authenticated/eods'
      path: '/eods'
      fullPath: '/eods'
      preLoaderRoute: typeof AuthenticatedEodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/csm': {
      id: '/_authenticated/csm'
      path: '/csm'
      fullPath: '/csm'
      preLoaderRoute: typeof AuthenticatedCsmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/closer-resources': {
      id: '/_authenticated/closer-resources'
      path: '/closer-resources'
      fullPath: '/closer-resources'
      preLoaderRoute: typeof AuthenticatedCloserResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/action-items': {
      id: '/_authenticated/action-items'
      path: '/action-items'
      fullPath: '/action-items'
      preLoaderRoute: typeof AuthenticatedActionItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies/': {
      id: '/_authenticated/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof AuthenticatedPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/api/public/google-oauth-callback': {
      id: '/api/public/google-oauth-callback'
      path: '/api/public/google-oauth-callback'
      fullPath: '/api/public/google-oauth-callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team_/$id': {
      id: '/_authenticated/team_/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof AuthenticatedTeamIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/requests': {
      id: '/_authenticated/students/requests'
      path: '/requests'
      fullPath: '/students/requests'
      preLoaderRoute: typeof AuthenticatedStudentsRequestsRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/sops/isa-setting-process': {
      id: '/_authenticated/sops/isa-setting-process'
      path: '/isa-setting-process'
      fullPath: '/sops/isa-setting-process'
      preLoaderRoute: typeof AuthenticatedSopsIsaSettingProcessRouteImport
      parentRoute: typeof AuthenticatedSopsRoute
    }
    '/_authenticated/sops/dm-setting-mastery': {
      id: '/_authenticated/sops/dm-setting-mastery'
      path: '/dm-setting-mastery'
      fullPath: '/sops/dm-setting-mastery'
      preLoaderRoute: typeof AuthenticatedSopsDmSettingMasteryRouteImport
      parentRoute: typeof AuthenticatedSopsRoute
    }
    '/_authenticated/policies/eod-hygiene': {
      id: '/_authenticated/policies/eod-hygiene'
      path: '/eod-hygiene'
      fullPath: '/policies/eod-hygiene'
      preLoaderRoute: typeof AuthenticatedPoliciesEodHygieneRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/policies/crm-hygiene': {
      id: '/_authenticated/policies/crm-hygiene'
      path: '/crm-hygiene'
      fullPath: '/policies/crm-hygiene'
      preLoaderRoute: typeof AuthenticatedPoliciesCrmHygieneRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/knowledge/new': {
      id: '/_authenticated/knowledge/new'
      path: '/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof AuthenticatedKnowledgeNewRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/knowledge/$slug': {
      id: '/_authenticated/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof AuthenticatedKnowledgeSlugRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/knowledge/$slug/edit': {
      id: '/_authenticated/knowledge/$slug/edit'
      path: '/edit'
      fullPath: '/knowledge/$slug/edit'
      preLoaderRoute: typeof AuthenticatedKnowledgeSlugEditRouteImport
      parentRoute: typeof AuthenticatedKnowledgeSlugRoute
    }
  }
}

interface AuthenticatedKnowledgeSlugRouteChildren {
  AuthenticatedKnowledgeSlugEditRoute: typeof AuthenticatedKnowledgeSlugEditRoute
}

const AuthenticatedKnowledgeSlugRouteChildren: AuthenticatedKnowledgeSlugRouteChildren =
  {
    AuthenticatedKnowledgeSlugEditRoute: AuthenticatedKnowledgeSlugEditRoute,
  }

const AuthenticatedKnowledgeSlugRouteWithChildren =
  AuthenticatedKnowledgeSlugRoute._addFileChildren(
    AuthenticatedKnowledgeSlugRouteChildren,
  )

interface AuthenticatedKnowledgeRouteChildren {
  AuthenticatedKnowledgeSlugRoute: typeof AuthenticatedKnowledgeSlugRouteWithChildren
  AuthenticatedKnowledgeNewRoute: typeof AuthenticatedKnowledgeNewRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
}

const AuthenticatedKnowledgeRouteChildren: AuthenticatedKnowledgeRouteChildren =
  {
    AuthenticatedKnowledgeSlugRoute:
      AuthenticatedKnowledgeSlugRouteWithChildren,
    AuthenticatedKnowledgeNewRoute: AuthenticatedKnowledgeNewRoute,
    AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  }

const AuthenticatedKnowledgeRouteWithChildren =
  AuthenticatedKnowledgeRoute._addFileChildren(
    AuthenticatedKnowledgeRouteChildren,
  )

interface AuthenticatedPoliciesRouteChildren {
  AuthenticatedPoliciesCrmHygieneRoute: typeof AuthenticatedPoliciesCrmHygieneRoute
  AuthenticatedPoliciesEodHygieneRoute: typeof AuthenticatedPoliciesEodHygieneRoute
  AuthenticatedPoliciesIndexRoute: typeof AuthenticatedPoliciesIndexRoute
}

const AuthenticatedPoliciesRouteChildren: AuthenticatedPoliciesRouteChildren = {
  AuthenticatedPoliciesCrmHygieneRoute: AuthenticatedPoliciesCrmHygieneRoute,
  AuthenticatedPoliciesEodHygieneRoute: AuthenticatedPoliciesEodHygieneRoute,
  AuthenticatedPoliciesIndexRoute: AuthenticatedPoliciesIndexRoute,
}

const AuthenticatedPoliciesRouteWithChildren =
  AuthenticatedPoliciesRoute._addFileChildren(
    AuthenticatedPoliciesRouteChildren,
  )

interface AuthenticatedSopsRouteChildren {
  AuthenticatedSopsDmSettingMasteryRoute: typeof AuthenticatedSopsDmSettingMasteryRoute
  AuthenticatedSopsIsaSettingProcessRoute: typeof AuthenticatedSopsIsaSettingProcessRoute
}

const AuthenticatedSopsRouteChildren: AuthenticatedSopsRouteChildren = {
  AuthenticatedSopsDmSettingMasteryRoute:
    AuthenticatedSopsDmSettingMasteryRoute,
  AuthenticatedSopsIsaSettingProcessRoute:
    AuthenticatedSopsIsaSettingProcessRoute,
}

const AuthenticatedSopsRouteWithChildren =
  AuthenticatedSopsRoute._addFileChildren(AuthenticatedSopsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedStudentsRequestsRoute: typeof AuthenticatedStudentsRequestsRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedStudentsRequestsRoute: AuthenticatedStudentsRequestsRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActionItemsRoute: typeof AuthenticatedActionItemsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCloserResourcesRoute: typeof AuthenticatedCloserResourcesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedCsmRoute: typeof AuthenticatedCsmRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRoute
  AuthenticatedEodsRoute: typeof AuthenticatedEodsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInstallmentsRoute: typeof AuthenticatedInstallmentsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRouteWithChildren
  AuthenticatedMochiRoute: typeof AuthenticatedMochiRoute
  AuthenticatedPayoutsRoute: typeof AuthenticatedPayoutsRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSalesHqRoute: typeof AuthenticatedSalesHqRoute
  AuthenticatedSopsRoute: typeof AuthenticatedSopsRouteWithChildren
  AuthenticatedStudentPortalRoute: typeof AuthenticatedStudentPortalRoute
  AuthenticatedStudentSuccessRoute: typeof AuthenticatedStudentSuccessRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTestimonialsRoute: typeof AuthenticatedTestimonialsRoute
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRoute
  AuthenticatedTeamIdRoute: typeof AuthenticatedTeamIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActionItemsRoute: AuthenticatedActionItemsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCloserResourcesRoute: AuthenticatedCloserResourcesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedCsmRoute: AuthenticatedCsmRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRoute,
  AuthenticatedEodsRoute: AuthenticatedEodsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInstallmentsRoute: AuthenticatedInstallmentsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRouteWithChildren,
  AuthenticatedMochiRoute: AuthenticatedMochiRoute,
  AuthenticatedPayoutsRoute: AuthenticatedPayoutsRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSalesHqRoute: AuthenticatedSalesHqRoute,
  AuthenticatedSopsRoute: AuthenticatedSopsRouteWithChildren,
  AuthenticatedStudentPortalRoute: AuthenticatedStudentPortalRoute,
  AuthenticatedStudentSuccessRoute: AuthenticatedStudentSuccessRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTestimonialsRoute: AuthenticatedTestimonialsRoute,
  AuthenticatedWorkRoute: AuthenticatedWorkRoute,
  AuthenticatedTeamIdRoute: AuthenticatedTeamIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PrintRoute: PrintRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
