/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintRouteImport } from './routes/print'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated.training'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated.team'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated.students'
import { Route as AuthenticatedSopsRouteImport } from './routes/_authenticated.sops'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated.policies'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated.notes'
import { Route as AuthenticatedEodsRouteImport } from './routes/_authenticated.eods'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated.crm'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedPoliciesIndexRouteImport } from './routes/_authenticated.policies.index'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google-oauth-callback'
import { Route as AuthenticatedSopsIsaSettingProcessRouteImport } from './routes/_authenticated.sops.isa-setting-process'
import { Route as AuthenticatedPoliciesCrmHygieneRouteImport } from './routes/_authenticated.policies.crm-hygiene'

const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSopsRoute = AuthenticatedSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEodsRoute = AuthenticatedEodsRouteImport.update({
  id: '/eods',
  path: '/eods',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoliciesIndexRoute =
  AuthenticatedPoliciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google-oauth-callback',
    path: '/api/public/google-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSopsIsaSettingProcessRoute =
  AuthenticatedSopsIsaSettingProcessRouteImport.update({
    id: '/isa-setting-process',
    path: '/isa-setting-process',
    getParentRoute: () => AuthenticatedSopsRoute,
  } as any)
const AuthenticatedPoliciesCrmHygieneRoute =
  AuthenticatedPoliciesCrmHygieneRouteImport.update({
    id: '/crm-hygiene',
    path: '/crm-hygiene',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/print': typeof PrintRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eods': typeof AuthenticatedEodsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/sops': typeof AuthenticatedSopsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/policies/crm-hygiene': typeof AuthenticatedPoliciesCrmHygieneRoute
  '/sops/isa-setting-process': typeof AuthenticatedSopsIsaSettingProcessRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/policies/': typeof AuthenticatedPoliciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/print': typeof PrintRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eods': typeof AuthenticatedEodsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/sops': typeof AuthenticatedSopsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/policies/crm-hygiene': typeof AuthenticatedPoliciesCrmHygieneRoute
  '/sops/isa-setting-process': typeof AuthenticatedSopsIsaSettingProcessRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/policies': typeof AuthenticatedPoliciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/print': typeof PrintRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eods': typeof AuthenticatedEodsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/_authenticated/sops': typeof AuthenticatedSopsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/policies/crm-hygiene': typeof AuthenticatedPoliciesCrmHygieneRoute
  '/_authenticated/sops/isa-setting-process': typeof AuthenticatedSopsIsaSettingProcessRoute
  '/api/public/google-oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/_authenticated/policies/': typeof AuthenticatedPoliciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/print'
    | '/admin'
    | '/analytics'
    | '/calendar'
    | '/crm'
    | '/dashboard'
    | '/eods'
    | '/notes'
    | '/policies'
    | '/sops'
    | '/students'
    | '/team'
    | '/training'
    | '/policies/crm-hygiene'
    | '/sops/isa-setting-process'
    | '/api/public/google-oauth-callback'
    | '/policies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/print'
    | '/admin'
    | '/analytics'
    | '/calendar'
    | '/crm'
    | '/dashboard'
    | '/eods'
    | '/notes'
    | '/sops'
    | '/students'
    | '/team'
    | '/training'
    | '/policies/crm-hygiene'
    | '/sops/isa-setting-process'
    | '/api/public/google-oauth-callback'
    | '/policies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/print'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/eods'
    | '/_authenticated/notes'
    | '/_authenticated/policies'
    | '/_authenticated/sops'
    | '/_authenticated/students'
    | '/_authenticated/team'
    | '/_authenticated/training'
    | '/_authenticated/policies/crm-hygiene'
    | '/_authenticated/sops/isa-setting-process'
    | '/api/public/google-oauth-callback'
    | '/_authenticated/policies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrintRoute: typeof PrintRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sops': {
      id: '/_authenticated/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof AuthenticatedSopsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eods': {
      id: '/_authenticated/eods'
      path: '/eods'
      fullPath: '/eods'
      preLoaderRoute: typeof AuthenticatedEodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies/': {
      id: '/_authenticated/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof AuthenticatedPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/api/public/google-oauth-callback': {
      id: '/api/public/google-oauth-callback'
      path: '/api/public/google-oauth-callback'
      fullPath: '/api/public/google-oauth-callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sops/isa-setting-process': {
      id: '/_authenticated/sops/isa-setting-process'
      path: '/isa-setting-process'
      fullPath: '/sops/isa-setting-process'
      preLoaderRoute: typeof AuthenticatedSopsIsaSettingProcessRouteImport
      parentRoute: typeof AuthenticatedSopsRoute
    }
    '/_authenticated/policies/crm-hygiene': {
      id: '/_authenticated/policies/crm-hygiene'
      path: '/crm-hygiene'
      fullPath: '/policies/crm-hygiene'
      preLoaderRoute: typeof AuthenticatedPoliciesCrmHygieneRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
  }
}

interface AuthenticatedPoliciesRouteChildren {
  AuthenticatedPoliciesCrmHygieneRoute: typeof AuthenticatedPoliciesCrmHygieneRoute
  AuthenticatedPoliciesIndexRoute: typeof AuthenticatedPoliciesIndexRoute
}

const AuthenticatedPoliciesRouteChildren: AuthenticatedPoliciesRouteChildren = {
  AuthenticatedPoliciesCrmHygieneRoute: AuthenticatedPoliciesCrmHygieneRoute,
  AuthenticatedPoliciesIndexRoute: AuthenticatedPoliciesIndexRoute,
}

const AuthenticatedPoliciesRouteWithChildren =
  AuthenticatedPoliciesRoute._addFileChildren(
    AuthenticatedPoliciesRouteChildren,
  )

interface AuthenticatedSopsRouteChildren {
  AuthenticatedSopsIsaSettingProcessRoute: typeof AuthenticatedSopsIsaSettingProcessRoute
}

const AuthenticatedSopsRouteChildren: AuthenticatedSopsRouteChildren = {
  AuthenticatedSopsIsaSettingProcessRoute:
    AuthenticatedSopsIsaSettingProcessRoute,
}

const AuthenticatedSopsRouteWithChildren =
  AuthenticatedSopsRoute._addFileChildren(AuthenticatedSopsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEodsRoute: typeof AuthenticatedEodsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRouteWithChildren
  AuthenticatedSopsRoute: typeof AuthenticatedSopsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEodsRoute: AuthenticatedEodsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRouteWithChildren,
  AuthenticatedSopsRoute: AuthenticatedSopsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PrintRoute: PrintRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
